filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    stream: all

    processors:
      - add_docker_metadata: ~
      - decode_json_fields:
          fields: ["message"]
          target: "json"
          overwrite_keys: false
          when:
            has_fields: ["message"]

      # Removed filter to capture all container logs
      # - drop_event:
      #     when:
      #       not:
      #         or:
      #           - contains:
      #               container.name: "dataops-assistant"
      #           - contains:
      #               container.name: "airflow"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "docker-logs-%{+yyyy.MM.dd}"

setup.ilm.enabled: false

setup.template.enabled: true
setup.template.name: "docker-logs"
setup.template.pattern: "docker-logs-*"

setup.kibana:
  host: "http://kibana:5601"

logging.level: info
