# Database Configuration for Data Loaders
database:
  # Connection settings
  connection:
    host: localhost
    port: 5432
    database: dataops_db
    user: dataops_user
    password: dataops_password

  # Connection pool settings
  pool:
    min_connections: 1
    max_connections: 10
    connection_timeout: 30

  # Loading settings
  loading:
    batch_size: 1000
    max_retries: 3
    retry_delay: 5

  # Table configurations
  tables:
    bank_transactions:
      primary_key: transaction_id
      indexes:
        - user_id
        - transaction_date
        - merchant
        - category
        - status
      constraints:
        required_fields:
          - transaction_id
          - user_id
          - account_id
          - transaction_date
          - amount
        data_types:
          user_id: integer
          account_id: integer
          amount: decimal
          transaction_date: date
          transaction_time: time

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "../logs/data_loader.log"
  max_file_size: 10MB
  backup_count: 5
