# This Dockerfile sets up Airflow with the requirements
FROM apache/airflow:2.9.0-python3.11
USER airflow
COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt
USER airflow
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
